# Generated by Django 4.2.7 on 2023-12-05 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_status_step_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="status",
        ),
    ]
