# Generated by Django 4.2.7 on 2023-12-05 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0004_remove_step_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status",
                to="todo.status",
            ),
        ),
    ]
