# Generated by Django 4.2.7 on 2023-11-27 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_customerloan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="title",
        ),
    ]
