# Generated by Django 4.2.7 on 2023-11-30 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_rename_title_company_name_alter_customerloan_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="age",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="name",
        ),
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="номер"),
        ),
        migrations.AddField(
            model_name="customer",
            name="arbitration_court",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_arbitration_court",
                to="customers.company",
                verbose_name="Арбитражный суд",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="birthdate",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата рождения"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="birthplace",
            field=models.CharField(default="", max_length=255, verbose_name="номер"),
        ),
        migrations.AddField(
            model_name="customer",
            name="comments",
            field=models.TextField(
                default="", max_length=1000, verbose_name="Комментарий"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(default="", max_length=50, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="customer",
            name="gosuslugi",
            field=models.CharField(default="", max_length=50, verbose_name="Госуслуги"),
        ),
        migrations.AddField(
            model_name="customer",
            name="job",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_job",
                to="customers.company",
                verbose_name="Место работы",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="middle_name",
            field=models.CharField(default="", max_length=50, verbose_name="Отчество"),
        ),
        migrations.AddField(
            model_name="customer",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("employed", "Работает"),
                    ("unemployed", "Безработный"),
                    ("pensioner", "Пенсионер"),
                    ("employed_pensioner", "Работающий пенсионер"),
                ],
                default="unemployed",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_issue_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="дата выдачи"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_issuer",
            field=models.CharField(
                default="", max_length=100, verbose_name="кем выдан"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_issuer_code",
            field=models.CharField(default="", max_length=6, verbose_name="номер"),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_number",
            field=models.CharField(default="", max_length=6, verbose_name="номер"),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_series",
            field=models.CharField(default="", max_length=5, verbose_name="серия"),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(default="", max_length=20, verbose_name="Телефон"),
        ),
        migrations.AddField(
            model_name="customer",
            name="position",
            field=models.CharField(
                default="", max_length=100, verbose_name="Должность"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="previous_year_income",
            field=models.FloatField(default=0, verbose_name="Доход за прошлый год"),
        ),
        migrations.AddField(
            model_name="customer",
            name="sex",
            field=models.CharField(
                choices=[("male", "муж"), ("female", "жен")],
                default="male",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="snils",
            field=models.CharField(default="", max_length=11, verbose_name="СНИЛС"),
        ),
        migrations.AddField(
            model_name="customer",
            name="sro",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_sro",
                to="customers.company",
                verbose_name="СРО",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="surname",
            field=models.CharField(default="", max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_id",
            field=models.CharField(default="", max_length=12, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="customer",
            name="tax_inspection",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_tax_inspection",
                to="customers.company",
                verbose_name="Налоговая",
            ),
        ),
        migrations.AlterField(
            model_name="customerloan",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.company",
                verbose_name="Кредитор",
            ),
        ),
    ]
