# Generated by Django 4.2.7 on 2023-11-30 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_remove_customer_age_remove_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="application_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата подачи заявления"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="birthplace",
            field=models.CharField(
                default="", max_length=255, verbose_name="Место рождения"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("employed", "Работает"),
                    ("unemployed", "Безработный"),
                    ("pensioner", "Пенсионер"),
                    ("employed_pensioner", "Работающий пенсионер"),
                ],
                default="unemployed",
                max_length=50,
                verbose_name="Место работы",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sex",
            field=models.CharField(
                choices=[("male", "муж"), ("female", "жен")],
                default="male",
                max_length=6,
                verbose_name="Пол",
            ),
        ),
    ]
