# Generated by Django 4.2.7 on 2023-12-01 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_alter_customer_passport_issuer_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerrealty",
            name="cost",
        ),
        migrations.AddField(
            model_name="customer",
            name="is_married",
            field=models.BooleanField(default=False, verbose_name="Состоит в браке"),
        ),
        migrations.AddField(
            model_name="customer",
            name="spouse_name",
            field=models.CharField(
                default="", max_length=100, verbose_name="ФИО супруга (-и)"
            ),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="acquiring_basis",
            field=models.CharField(
                default="", max_length=255, verbose_name="Основание приобретения"
            ),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="address",
            field=models.CharField(default="", max_length=255, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="area",
            field=models.FloatField(default=0, verbose_name="Площадь"),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="pledge",
            field=models.CharField(
                default="", max_length=100, verbose_name="Сведения о залоге"
            ),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("individual", "Индивидуальная"),
                    ("joint", "Общая совместная"),
                ],
                default="individual",
                max_length=30,
                verbose_name="Вид собственности",
            ),
        ),
        migrations.AddField(
            model_name="customerrealty",
            name="type",
            field=models.CharField(
                choices=[
                    ("land_plot", "Земельный участок"),
                    ("house", "Жилой дом, дача"),
                    ("apartment", "Квартира"),
                    ("garage", "Гараж"),
                    ("other", "Иное недвижимое имущество"),
                ],
                default="apartment",
                max_length=30,
                verbose_name="Вид имущества",
            ),
        ),
        migrations.AlterField(
            model_name="customerrealty",
            name="name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Наименование"
            ),
        ),
        migrations.CreateModel(
            name="CustomerTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Наименование"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("car", "Автомобиль легковой"),
                            ("truck", "Автомобиль грузовой"),
                            ("motobike", "Мототранспортное средство"),
                            ("agriculturtal_machinery", "Сельскохозяйственная техника"),
                            ("boat", "Водный транспорт"),
                            ("plane", "Воздушный транспорт"),
                            ("other", "Иное транспортное средство"),
                        ],
                        default="car",
                        max_length=30,
                        verbose_name="Вид имущества",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("individual", "Индивидуальная"),
                            ("joint", "Общая совместная"),
                        ],
                        default="individual",
                        max_length=30,
                        verbose_name="Вид собственности",
                    ),
                ),
                ("cost", models.FloatField(default=0, verbose_name="Площадь")),
                (
                    "production_year",
                    models.CharField(
                        default="", max_length=4, verbose_name="Основание приобретения"
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(
                        default="", max_length=20, verbose_name="Основание приобретения"
                    ),
                ),
                (
                    "pledge",
                    models.CharField(
                        default="", max_length=100, verbose_name="Сведения о залоге"
                    ),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=255, verbose_name="Адрес"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit", "кредит"),
                            ("loan", "заeм"),
                            ("credit_card", "кредитная карта"),
                            ("utilities", "коммунальные услуги"),
                            ("tax", "налог"),
                        ],
                        default="credit",
                        max_length=30,
                        verbose_name="Вид счета",
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        default="",
                        max_length=255,
                        verbose_name="Основание возникновения",
                    ),
                ),
                (
                    "gross_amount",
                    models.FloatField(default=0, verbose_name="Сумма всего"),
                ),
                (
                    "net_amount",
                    models.FloatField(default=0, verbose_name="в т.ч. задолженность"),
                ),
                (
                    "penalties_amount",
                    models.FloatField(default=0, verbose_name="в т.ч. штрафы, пени"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
                (
                    "lender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                        verbose_name="Кредитор",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerMandatoryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_name",
                    models.CharField(
                        choices=[
                            ("transport_tax", "транспортный налог"),
                            ("land_tax", "земельный налог"),
                            ("property_tax", "налог на имущество"),
                        ],
                        default="transport_tax",
                        max_length=100,
                        verbose_name="Наименование налога (сбора)",
                    ),
                ),
                (
                    "arrears_amount",
                    models.FloatField(default=0, verbose_name="Недоимка"),
                ),
                (
                    "penalties_amount",
                    models.FloatField(default=0, verbose_name="Штрафы, пени"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerExecutiveDoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("resolution", "постановление"),
                            ("court_order", "судебный приказ"),
                            ("execution_writ", "исполнительный лист"),
                        ],
                        default="resolution",
                        max_length=30,
                        verbose_name="Вид документа",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Дата"),
                ),
                (
                    "doc_number",
                    models.CharField(default="", max_length=20, verbose_name="Номер"),
                ),
                (
                    "executor",
                    models.CharField(default="", max_length=100, verbose_name="Номер"),
                ),
                (
                    "content",
                    models.CharField(default="", max_length=255, verbose_name="Номер"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="ФИО"),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "муж"), ("female", "жен")],
                        default="male",
                        max_length=6,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomerBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "вклад"), ("current", "текущий")],
                        default="current",
                        max_length=10,
                        verbose_name="Вид счета",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("rur", "руб.")],
                        default="rur",
                        max_length=10,
                        verbose_name="Валюта счета",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        default="", max_length=20, verbose_name="Номер счета"
                    ),
                ),
                ("balance", models.FloatField(default=0, verbose_name="Сумма")),
                (
                    "opening_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Дата открытия"
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.company",
                        verbose_name="Банк",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
