# Generated by Django 4.2.7 on 2023-12-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0012_alter_customerexecutivedoc_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customertransport",
            name="cost",
            field=models.FloatField(default=0, verbose_name="Стоимость"),
        ),
        migrations.AlterField(
            model_name="customertransport",
            name="production_year",
            field=models.CharField(
                default="", max_length=4, verbose_name="Год выпуска"
            ),
        ),
    ]
